// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADEivr3TOQ_G7_hmUApUW3zck-9SrFbYI',
    appId: '1:739229502650:web:59b1db846cf1c1be1b0683',
    messagingSenderId: '739229502650',
    projectId: 'timerg-a31ec',
    authDomain: 'timerg-a31ec.firebaseapp.com',
    databaseURL: 'https://timerg-a31ec-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'timerg-a31ec.appspot.com',
    measurementId: 'G-C9VGV19M67',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9XGHReZ7QmYnS3rILkC9j4atVquJ5_QU',
    appId: '1:739229502650:android:b049177e671ac3261b0683',
    messagingSenderId: '739229502650',
    projectId: 'timerg-a31ec',
    databaseURL: 'https://timerg-a31ec-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'timerg-a31ec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFTxGmT8odV_xBOxNf21s3mY_yVsz6Mhk',
    appId: '1:739229502650:ios:209ca0d5dace061a1b0683',
    messagingSenderId: '739229502650',
    projectId: 'timerg-a31ec',
    databaseURL: 'https://timerg-a31ec-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'timerg-a31ec.appspot.com',
    iosClientId: '739229502650-3m8rn6397hav2m9s4sasuqhusel37rc1.apps.googleusercontent.com',
    iosBundleId: 'com.example.timerg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFTxGmT8odV_xBOxNf21s3mY_yVsz6Mhk',
    appId: '1:739229502650:ios:d50b74863a2083c61b0683',
    messagingSenderId: '739229502650',
    projectId: 'timerg-a31ec',
    databaseURL: 'https://timerg-a31ec-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'timerg-a31ec.appspot.com',
    iosClientId: '739229502650-98ov9nmb0en0pv83e8t9gvdp6mocmqk2.apps.googleusercontent.com',
    iosBundleId: 'com.example.timerg.RunnerTests',
  );
}
